development:
  adapter: postgresql
  encoding: utf8
  database: project_development
  pool: 5
  username: sadda 
  password: saddasadda1

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username: sadda
  password: saddasadda1

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  pool: 5
  username: sadda
  password: saddasadda1

cucumber:
  <<: *TEST